function [multiIndex, nBasis] = initMultiIndex(nord, ndim)
% function: initMultiIndex
% purpose:  returns the multi-index for the multi-dimensional basis 
%           
% usage: [multiIndex, nBasis] = initMultiIndex(nord, ndim) 
%
% input: 
%    nord: order of expansion
%    ndim: stochastic dimension
%
% output:
%    multiIndex: multi-index matrix 
%    nBasis: number of terms in the expansion.


maxP = 200;
multiIndex = zeros(maxP, ndim);
%       zero-th order term

nBasis = 1;                 % nBasis = 1  corresponds to zero order term
np(nBasis) = 0;             % order of term nBasis
for i = 1 : ndim
   multiIndex(nBasis,i) = 0;
end

nn(0+1) = 1;               % number of terms of order 0

if (nord > 0) 
%          first order terms

   for j = 1 : ndim
      nBasis = nBasis+1;
      np(nBasis) = 1;          % order of term nBasis

      for i = 1 : j-1      % multi_index(nBasis,j)=delta_nBasis,j
         multiIndex(nBasis,i)=0;
      end

      multiIndex(nBasis,j) = 1;

      for i = j+1 : ndim
         multiIndex(nBasis,i)=0;
      end 
   end

   for i = 1 : ndim
      ic(i) = 1;           % number of terms of this order generated by
                           % increasing order of dimension i by one
                           % in the terms of previous order
   end

   nn(1+1) = ndim;         % number of terms of order 1

   if(nord > 1)
      % higher order terms

      for k = 2 : nord

         IP = nBasis;         %number of terms with order less than k

         for j=1 : ndim
            isum = 0;
            for l = ndim : -1 : j
               isum = isum + ic(l);
            end
            ict(j) = isum;
         end

         for j = 1 : ndim
            ic(j) = ict(j);   %number of terms of this order generated by
                              %increasing order of dimension i by one
                              %in the terms of previous order
         end

         for jj = 1 : ndim
            for j = IP-ic(jj)+1 : IP       %get next ic(jj) terms by increasing order
                                           %of dimension jj in the last ic(jj) terms
                                           %of the previous order
               nBasis = nBasis+1;
               np(nBasis) = k;                 % order of this term
               for i = 1 : ndim
                  multiIndex(nBasis,i) = multiIndex(j,i);
               end
               multiIndex(nBasis,jj) = multiIndex(nBasis,jj)+1;    %increase order of dimension jj
                                              %by one to get the next term
            end
         end
         nn(k+1) = nBasis - IP;                  %number of terms with order k
      end
   end
end     

% cut the unused part of the matrix
multiIndex = multiIndex(1:nBasis, :);
